# Generated by Django 2.1.7 on 2019-07-30 22:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(default=datetime.datetime(2019, 7, 30, 22, 11, 20, 937797, tzinfo=utc), verbose_name='Date Created')),
                ('category_parent', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='main.Category')),
                ('created_by', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
