# Generated by Django 2.1.7 on 2019-07-30 22:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190730_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_parent',
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_by',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 30, 22, 19, 43, 113387, tzinfo=utc), verbose_name='Date Created'),
        ),
    ]
