# Generated by Django 2.1.7 on 2019-07-31 01:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190730_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 31, 1, 56, 52, 393313, tzinfo=utc), verbose_name='Date Created'),
        ),
    ]
