# Generated by Django 2.1.7 on 2019-07-31 03:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190731_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_address',
            field=models.TextField(blank=True, default='img/sample.jpg'),
        ),
        migrations.AlterField(
            model_name='category',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 31, 3, 47, 34, 648818, tzinfo=utc), verbose_name='Date Created'),
        ),
    ]
