# Generated by Django 2.1.7 on 2019-07-31 19:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190731_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='classification_type',
            field=models.CharField(default='Class', max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 31, 19, 26, 9, 665636, tzinfo=utc), verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image_address',
            field=models.CharField(blank=True, default='none', max_length=200),
        ),
    ]
