# Generated by Django 2.1.7 on 2019-07-31 20:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190731_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 31, 20, 31, 14, 221439, tzinfo=utc), verbose_name='Date Created'),
        ),
    ]
