# Generated by Django 2.1.7 on 2019-07-31 20:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190731_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 31, 20, 35, 46, 495729, tzinfo=utc), verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image_description',
            field=models.CharField(default='', max_length=400),
        ),
    ]
