# Generated by Django 2.1.7 on 2019-08-02 03:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20190731_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 2, 3, 25, 10, 689416, tzinfo=utc), verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image_description',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
    ]
